[9.0][NEW] account_bank _statement_import_move_line
OCA/bank-statement-import pull request #120
Opened 2017-07-30 10:16 UTC by luismontalba

Account Bank Statement Import Move Line
==================================

This module adds a button to bank statement form to open a wizard to allow filtration, selection and importation of lines form journal items into the bank statement.

Usage
--------

* Go to Invoicing > Dashboard.
* Create a new bank statement from a bank journal.
* Click button "Import Journal Items".
* Select filtering options.
* Click on button "Add All Move Lines" to auto-select the move lines matching
 the selected criteria or click on Add an item to manually select the move
 lines filtered by the criteria.
* Click on button "Create Statement Lines".

cc @Tecnativa

2017-07-31 10:46 UTC, pedrobaeza requested changes
Little changes on code review

@chienandalu please make a functional review

2017-07-31 10:46 UTC, pedrobaeza commented on account_bank_statement_import_move_line/README.rst
> +filtration, selection and importation of lines form journal items into the
s/filtration/filtering

2017-07-31 10:46 UTC, pedrobaeza commented on account_bank_statement_import_move_line/README.rst
> +filtration, selection and importation of lines form journal items into the
s/form/from

2017-07-31 10:46 UTC, pedrobaeza commented on account_bank_statement_import_move_line/README.rst
> + the selected criteria or click on Add an item to manually select the move
For second line and successive, you have to indent 2 spaces.

2017-07-31 10:48 UTC, pedrobaeza commented
Please check also Travis status

2017-07-31 14:13 UTC, chienandalu approved these changes
Functional review :+1:

2017-08-01 18:02 UTC, pedrobaeza approved these changes

2017-08-01 18:02 UTC, pedrobaeza commented
Please port it also to v10.

2017-08-01 23:47 UTC, alexis-via commented on account_bank_statement_import_move_line/README.rst
> +filtering, selecting and importing lines form journal items into the bank
form -> from ?

2017-08-05 09:09 UTC, luismontalba commented on account_bank_statement_import_move_line/README.rst
> +filtering, selecting and importing lines form journal items into the bank
Form view (now clarified in the README)

2017-08-05 09:09 UTC, luismontalba commented
Changes done and test added (commit squashed)

2017-08-07 15:09 UTC, merged