[10.0][NEW] account_bank_statement_import_move_line
OCA/bank-statement-import pull request #121
Opened 2017-08-05 18:33 UTC by luismontalba

Account Bank Statement Import Move Line
==================================
This module adds a button to bank statement form view to open a wizard to allow filtering, selecting and importing lines form journal items into the bank statement.

Usage
--------
* Go to Invoicing > Dashboard.
* Create a new bank statement from a bank journal.
* Click button "Import Journal Items".
* Select filtering options.
* Click on button "Add All Move Lines" to auto-select the move lines matching the selected criteria or click on "Add an item" to manually select the move lines filtered by the criteria.
* Click on button "Create Statement Lines".

cc @Tecnativa

2017-08-07 15:08 UTC, pedrobaeza approved these changes
Next time, let 9.0 commit, and create another commit with the 10.0 migration.

@cubells @chienandalu please review

2017-08-07 15:52 UTC, cubells requested changes
Minor changes.

2017-08-07 15:52 UTC, cubells commented on account_bank_statement_import_move_line/README.rst
> +check there if your issue has already been reported. If you spotted it first,
Reformat this line break

2017-08-07 15:52 UTC, cubells commented on account_bank_statement_import_move_line/i18n/es.po
> +"Project-Id-Version: Odoo Server 9.0c\n"
Translation is not updated?

2017-08-07 15:52 UTC, cubells commented on account_bank_statement_import_move_line/tests/test_account_bank_statement_import_move_line.py
> +            'account_id': cls.a_receivable.id,
There is not exist a field "account_id" in res_partner model. Is It necessary that field?

2017-08-09 15:47 UTC, luismontalba commented
Translation updated and changes proposed done (commit squashed).

2017-08-09 15:57 UTC, luismontalba commented
Travis log:

/home/travis/maintainer-quality-tools/travis/travis_install_nightly: line 21:  4721 Segmentation fault      (core dumped) npm install -g eslint
The command "travis_install_nightly" failed and exited with 139 during .
Your build has been stopped.

2017-08-09 15:58 UTC, cubells approved these changes
:+1: 

LGTM

Code review and test.

2017-08-09 16:02 UTC, chienandalu approved these changes
Tested on runbot :+1: 
Travis error seems to be unrelated

2017-08-10 08:02 UTC, pedrobaeza commented
I have relaunched Travis pyltint state and is OK now (a temporary glitch?), so I merge.

2017-08-10 08:02 UTC, merged