[10.0] [FIX] Solve encoding issue and add AMEX support
OCA/bank-statement-import pull request #132
Opened 2017-11-21 11:43 UTC by sebastienbeau

This PR solve 2 issues:

- importing AMEX qif bank statement (header is CCARD)
- solving encoding issue by guessing it with the lib "chardet"

2017-11-21 11:46 UTC, pedrobaeza commented
Changing an external dependency in a stable version is not convenient, as it makes all existing installations to break.

2017-11-22 13:46 UTC, sebastienbeau commented
@pedrobaeza you are right, I can make it optionnal.

2017-11-22 14:31 UTC, sebastienbeau commented
I have changed my code, now I use utf-8 by default (this should work with the majority of case) if you had the chardet lib, it will try to guess the right encoding.
Also I have refactored the code to be able to inherit the way to parse the date in custom module

2017-11-22 16:18 UTC, pedrobaeza requested changes
And please change module version number

2017-11-22 16:18 UTC, pedrobaeza commented on account_bank_statement_import_qif/wizards/account_bank_statement_import_qif.py
> +    _logger.debug(err)
Put here `chardet = False` instead for easy handling

2017-11-22 16:18 UTC, pedrobaeza commented on account_bank_statement_import_qif/wizards/account_bank_statement_import_qif.py
> +        try:
Don't put the message each time. With the other change, you can do:
```
if chardet:
    chardet.detect(data_file)['encoding']
else:
    return 'utf-8'
```

2017-11-22 16:28 UTC, sebastienbeau commented
Thanks for your feedback Pedro !
I have done the fixes

2017-11-22 16:31 UTC, pedrobaeza approved these changes

2017-11-22 20:21 UTC, bealdav approved these changes

2017-12-11 16:42 UTC, merged