Add German date format
OCA/bank-statement-import pull request #222
Opened 2019-08-29 13:54 UTC by wildi1

2019-08-29 15:07 UTC, pedrobaeza approved these changes

2020-02-26 14:55 UTC, benbrich approved these changes
Just tested and it works fine! How about merging this one?

2020-03-03 19:48 UTC, benbrich commented
@pedrobaeza is there a reason, why not merging this one? Any Problems with the code in other countries?

2020-03-03 19:52 UTC, pedrobaeza commented
I'm not anymore OCA's community manager and I'm not monitoring PRs. This should corresponds to the PSC (as in the past, but I served as wildcard). I can do it one last time, but now this PR is contaminated with 4 commits more than when I approved it.

2020-03-03 19:52 UTC, pedrobaeza requested changes
Remove extra commits, that also performs other things.

2020-03-03 20:20 UTC, benbrich commented
Hi and thanks, I understand! Wanted to address @StefanRijnhart first, but thought you are on the PSC and on the topic. Couldn't find a maintainer in the readme. Will remember next time...

2020-03-03 20:21 UTC, benbrich commented
@wildi1 would be great if you could fix this soon! :-)

2020-03-03 21:35 UTC, StefanRijnhart commented on account_bank_statement_import_paypal/wizards/account_bank_statement_import_paypal.py
> +            if cline and (cline['amount'] * line['amount'] > 0):
I'm slightly puzzled by this line. It looks like you encountered a statement line with the currency amount having the wrong sign. Can you clarify this a bit, or even better, add a test for this situation?

2020-03-04 21:38 UTC, wildi1 commented
@pedrobaeza The first PR was made in Aug 19. I thought it will be merged soon after you approved it and so I forgot that it is not merged yet. Therfore my other Commits have contaminated this PR.

@StefanRijnhart This schould be part of an other Pull Request I already made. I have split them now in two separate PRs.

Here is the new PR for this request
#256

2020-03-04 21:38 UTC, closed without merging

2020-03-04 22:01 UTC, wildi1 commented
@StefanRijnhart Here is the other PR and the explenation of the behaviour with the wrong sign.
 #258

2020-03-04 22:04 UTC, wildi1 commented
@benbrich I have fixed it soon :) When you are using Paypal with different currencies you should also have a look at #258