[14.0][MIG] account_bank_statement_import
OCA/bank-statement-import pull request #359
Opened 2020-11-17 23:34 UTC by alexis-via

2020-11-18 07:04 UTC, alexey-pelykh approved these changes

2020-11-19 20:35 UTC, njeudy approved these changes
test and ok for me thanks @alexis-via

2020-12-06 17:33 UTC, i-vyshnevska requested changes
@alexis-via you need to keep the initial commit history

2020-12-06 17:33 UTC, i-vyshnevska commented on account_statement_import/i18n/account_bank_statement_import.pot
> +# Translation of Odoo Server.
remove file

2020-12-06 17:33 UTC, i-vyshnevska commented on account_statement_import/wizard/account_statement_import.py
> +                    -o 'note': string
field "note" was removed from the model

2020-12-14 19:20 UTC, luc-demeyer commented on account_statement_import/wizard/account_statement_import.py
> +            )
search returns recordset -> change to search([...]).ids

2021-01-05 12:07 UTC, luc-demeyer approved these changes

2021-01-05 12:10 UTC, luc-demeyer commented
@alexis-via 
note field has not been removed but is renamed to 'narration'

2021-01-05 12:10 UTC, pedrobaeza commented
Some git work is needed before merging:

- Change first commit author to be something like info@odoo.com for changing attribution.
- Pre-commit stuff should be before doing any change.
- Squash unneeded changes.

@alexis-via do you want me to do these changes?

2021-01-05 13:40 UTC, alexis-via commented
@pedrobaeza Yes, go ahead !

2021-01-06 14:37 UTC, fclementic2c commented
Hello, I would appreciate to have this PR merged quickly if possible. Thanks @alexis-via

2021-01-06 14:38 UTC, fclementic2c approved these changes

2021-01-07 08:30 UTC, pedrobaeza commented
As I can't push to this branch being a corporate branch (don't know why GitHub applies such constraint), I have opened #367, and I will directly merge it as this one has enough approvals.

2021-01-07 08:30 UTC, closed without merging