[14.0] [ADD] account statement import online ing
OCA/bank-statement-import pull request #432
Opened 2021-12-13 19:40 UTC by NL66278

Clear payment_ref of data also in other fields.

2021-12-13 19:41 UTC, NL66278 commented
Includes changes in https://github.com/OCA/bank-statement-import/pull/431

2022-04-12 09:02 UTC, StefanRijnhart requested changes
Looking good in principle, but can you rebase now that https://github.com/OCA/bank-statement-import/pull/431 is merged? The commit specific to this PR looks strange, as if it reverses the refactoring after the `if response.status_code == 200:` line.

2022-04-12 10:44 UTC, NL66278 commented
@StefanRijnhart  rebased and then manually reset the remaining unwanted change at the location you indicated.

2022-04-12 10:55 UTC, StefanRijnhart approved these changes
Thanks!

2022-06-13 03:56 UTC, alexey-pelykh requested changes

2022-06-13 03:56 UTC, alexey-pelykh commented on account_statement_import_online_ponto_ing/tests/test_account_statement_import_online_ponto.py
> +class TestAccountBankAccountStatementImportOnlineQonto(common.TransactionCase):
Qonto <> Ponto

2022-06-13 03:57 UTC, alexey-pelykh commented
Except one typo code is LGTM

2022-06-13 09:45 UTC, NL66278 commented
@alexey-pelykh I corrected it Thanks!

2022-06-13 10:06 UTC, alexey-pelykh approved these changes

2022-06-13 10:16 UTC, StefanRijnhart commented
/ocabot merge nobump

2022-06-13 10:41 UTC, merged