WIP: [14.0] account_bank_statement_import_camt : More verbose narration (notes)
OCA/bank-statement-import pull request #438
Opened 2022-01-09 19:28 UTC by TeoGoddet

2022-01-09 19:32 UTC, TeoGoddet commented
This is very similar #437, need to choose unify this work

2022-01-10 20:54 UTC, TeoGoddet commented
![image](https://user-images.githubusercontent.com/9885447/148837900-f6e8c2df-b62c-473d-90ba-355273eafc36.png)
Example of what it gives

2022-01-10 20:56 UTC, TeoGoddet commented
As discussed in #437
This PR introduce new infos in v14 narration bank statement field and is approximately a forward port of #437

2022-01-10 22:26 UTC, TeoGoddet commented
@luc-demeyer maybe you want to look at it now that's it ready

2022-01-11 18:38 UTC, luc-demeyer approved these changes

2022-04-12 08:53 UTC, StefanRijnhart requested changes
Nice one! Can you mention the module name in the commits  (see https://github.com/OCA/bank-statement-import/pull/437/commits for an example)?
I would prefer to have the commits squashed into one as well.

2022-04-18 20:19 UTC, TeoGoddet commented
Hello @StefanRijnhart thanks for the review, sorry for the bad commit name, I updated and squashed.
Have a nice day,

2022-05-15 14:07 UTC, StefanRijnhart approved these changes
Thanks for the update!

2022-06-11 18:50 UTC, TeoGoddet commented
Hello @OCA/banking-maintainers !
Can one of you merge or tell me if something is wrong ?
Thanks !

2022-06-12 20:14 UTC, alexey-pelykh approved these changes

2022-06-12 20:15 UTC, alexey-pelykh commented
/ocabot merge minor

2022-06-13 03:51 UTC, alexey-pelykh commented
@TeoGoddet merge won't happen until issue with this test is sorted out https://app.travis-ci.com/github/OCA/bank-statement-import/jobs/573268273#L1443

2022-06-13 10:18 UTC, StefanRijnhart commented
Ah yes, a rebase is needed and the additional data needs to be added to that recently added test fixture

2022-06-14 08:15 UTC, TeoGoddet commented
@alexey-pelykh Sorry the branch was a bit old, I rebased and updated the failing test with the new infos.
Thanks

2022-06-14 09:47 UTC, StefanRijnhart commented
/ocabot merge minor

2022-06-14 10:00 UTC, merged