[IMP] account_statment_import: Add button for importing on top
OCA/bank-statement-import pull request #522
Opened 2022-11-17 15:42 UTC by etobella

This PR has two goals:

- [x] Adding a button on the top of the Journal Dashboard to import files
- [ ] Block the import of statements from different journals if we use the one from the journal item

The main goal is to simplify the usage (and make it more consistent)

@pedrobaeza as talked on OCA/l10n-spain#2610

2022-11-17 15:55 UTC, etobella commented
![image](https://user-images.githubusercontent.com/28590170/202494535-44d38d2b-fcea-4f57-aab5-6f8f41814dbe.png)

2022-11-17 20:27 UTC, pedrobaeza requested changes

2022-11-17 20:27 UTC, pedrobaeza commented on account_statement_import/wizard/account_statement_import.py
> +            ):
```suggestion
            journal = self.env.context.get("journal_id")
            if journal and journal.id != journal:
```

2022-11-17 20:27 UTC, pedrobaeza commented on account_statement_import/wizard/account_statement_import.py
> +                        "The journal found for the file is not consisent with the "
```suggestion
                        "The journal found for the file is not consistent with the "
```

2022-11-17 20:27 UTC, pedrobaeza commented on account_statement_import/wizard/account_statement_import.py
> +                        "use the generic button on the top of Invoicing Dashboard"
```suggestion
                        "use the generic button on the top of the Accounting Dashboard"
```

2022-11-17 20:27 UTC, pedrobaeza commented on account_statement_import/wizard/account_statement_import_view.xml
> +
Extra empty lines not needed

2022-11-19 09:02 UTC, pedrobaeza approved these changes

2022-11-21 07:36 UTC, LoisRForgeFlow approved these changes
LGTM

2022-11-21 07:38 UTC, pedrobaeza commented
/ocabot merge minor

2022-11-21 07:46 UTC, merged