[16.0][mig] account_statement_import_paypal: Migration to 16.0
OCA/bank-statement-import pull request #609
Opened 2023-07-11 12:03 UTC by dsolanki-initos

2023-11-23 21:05 UTC, Abranes commented
@dsolanki-initos [`web_widget_dropdown_dynamic`](https://github.com/OCA/web/pull/2563) It's already merged, could you do a rebase?

2024-02-08 16:52 UTC, ACheung-FactorLibre requested changes
Hi @dsolanki-initos, could you please rebase? Thank you!

2024-02-08 16:52 UTC, ACheung-FactorLibre commented on account_statement_import_paypal/migrations/14.0.1.0.0/pre-migrate.py
Please remove this.
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch

2024-02-08 16:52 UTC, ACheung-FactorLibre commented on account_statement_import_paypal/models/account_statement_import.py
> +                    )
Could you store the result in a variable to avoid calling the method `parse()` twice?

2024-02-08 16:52 UTC, ACheung-FactorLibre commented on account_statement_import_paypal/wizards/account_statement_import_paypal_mapping_wizard.py
> +            self.note_column = header[21]
Could you do a `write()` over `self` with all modifications?

2024-02-08 16:52 UTC, ACheung-FactorLibre commented on account_statement_import_paypal/wizards/account_statement_import_paypal_mapping_wizard.py
> +            self.bank_account_column = header[13]
Same here. Could you do a `write()` over `self` with all modifications?

2024-07-14 12:30 UTC, closed without merging