[17.0][MIG] account_statement_import_file: Migration to 17.0
OCA/bank-statement-import pull request #649
Opened 2023-12-19 11:51 UTC by rov-adhoc

Depends on:

- [647] https://github.com/OCA/bank-statement-import/pull/647

2024-02-05 21:03 UTC, StefanRijnhart commented
@rov-adhoc Please rebase :smiley:

2024-02-06 11:20 UTC, rov-adhoc commented
@StefanRijnhart done!!

2024-04-09 10:12 UTC, xtanuiha commented
I have just updated the translation file for Simplified Chinese, could you please merge it into the code? Thank you!  @rov-adhoc 

[zh_CN.zip](https://github.com/OCA/bank-statement-import/files/14917186/zh_CN.zip)

2024-04-09 10:16 UTC, pedrobaeza commented
@xtanuiha please stop publishing that files here. Keep them and you upload them on Weblate once these modules are merged.

2024-04-11 06:42 UTC, xtanuiha commented
> @xtanuiha please stop publishing that files here. Keep them and you upload them on Weblate once these modules are merged.

Excuse me, I just found out that OCA has a Weblate platform for handling translations.

2024-04-22 07:37 UTC, hbrunn commented
/ocabot migration 17.0

2024-04-22 07:44 UTC, pedrobaeza commented
@hbrunn it's /ocabot migration account_statement_import_file

The version is taken from the target branch. What can't be guessed is the module name.

2024-04-22 09:29 UTC, hbrunn commented
@pedrobaeza ah thanks, I keep misremembering ocabot commands. nobump or nopatch and such.

2024-04-22 12:21 UTC, hbrunn requested changes
this module never had tests, because testing happens in derived modules like the [camt](https://github.com/OCA/bank-statement-import/pull/684) I just added on top of this - should we still add some tests here, mostly checking for error handling?

2024-04-22 12:21 UTC, hbrunn commented on account_statement_import_file/wizard/account_statement_import.py
> +        self.env["ir.attachment"].create(self._prepare_create_attachment(result))
since v16, there's a many2many field [attachment_ids](https://github.com/OCA/OCB/blob/17.0/addons/account/models/account_bank_statement.py#L101) on bank statements, and users would expect to find the file there. So please add this link, would make sense to add it for all created statements I think.

Please do so in a separate commit so that this is easy to cherry pick to v16.

2024-05-08 13:10 UTC, pedrobaeza commented
Superseded by #692

2024-05-08 13:10 UTC, closed without merging