17.0 mig account statement import online paypal
OCA/bank-statement-import pull request #722
Opened 2024-09-17 11:31 UTC by kvdveer

Basic migration, following the 17.0 guide

Also: a uses more reliable way to obtain name and email from the PayPal transaction data. (this is in a separate commit)

2024-09-17 12:20 UTC, kvdveer commented
/ocabot migration account_statement_import_online_paypal

2024-09-17 17:27 UTC, pedrobaeza commented
/ocabot migration account_statement_import_online_paypal

2025-01-14 14:24 UTC, DavidJForgeFlow approved these changes
Functional review :+1: Code also LGTM!

2025-03-03 09:38 UTC, sergijPf commented
functional review done (enterprise) - ok,
unit tests were run locally - ok,
noticed few updates in EVENT_DESCRIPTIONS (https://developer.paypal.com/docs/transaction-search/transaction-event-codes/)

2025-03-03 10:08 UTC, sergijPf approved these changes

2025-03-05 14:56 UTC, john-herholz-dt commented
@pedrobaeza if nothing speaks against it, could you merge it? We would like to use it in production.

Thank you!

2025-03-06 07:47 UTC, pedrobaeza commented on account_statement_import_online_paypal/models/online_bank_statement_provider_paypal.py
> +            note += f" ({payer_email or payer_full_name})"
Isn't more important the full name than the email?

2025-03-19 15:52 UTC, john-herholz-dt commented on account_statement_import_online_paypal/models/online_bank_statement_provider_paypal.py
> +            note += f" ({payer_email or payer_full_name})"
As PayPal accounts are identified by an e-mail, I would consider the payer_email with a higher priority

2025-07-03 07:00 UTC, DavidJForgeFlow commented
Hi @kvdveer I think you uploaded a wrong commit here: https://github.com/OCA/bank-statement-import/pull/722/commits/08a772801b4bece480b433cdf2760ffe77d609b9. Please remove it ASAP, thanks!

2025-07-03 07:13 UTC, kvdveer commented
@DavidJForgeFlow Is there still interest in this MR?
We're moving to odoo 18 - I don't actually plan on doing much work on this.

2025-07-03 07:38 UTC, DavidJForgeFlow commented
I mean, from my side I would like to get this merged. @pedrobaeza do you agree to merge?

2025-07-04 07:09 UTC, pedrobaeza requested changes
The migration changes have to be in a separate commit, and the rest of the commits should be squashed into that commit. You can explain the changes made in the own commit message.

2025-07-04 07:09 UTC, pedrobaeza commented on account_statement_import_online_paypal/__manifest__.py
> +    "version": "17.0.1.0.1",
17.0.1.0.0

2025-07-22 08:19 UTC, DavidJForgeFlow commented
@kvdveer could you please review latest feedback from @pedrobaeza? Thanks!

2025-10-13 07:07 UTC, DavidJForgeFlow commented
Hi @kvdveer, could you please change version? Thanks!

2026-01-14 11:50 UTC, ivs-cetmix commented
Hey @DavidJForgeFlow @pedrobaeza  we have opened https://github.com/OCA/bank-statement-import/pull/887 because this one looks abandoned. Would appreciate your review.

2026-01-14 12:36 UTC, closed without merging