[18.0][MIG] account_statement_import_sheet_file: Migration to 18.0
OCA/bank-statement-import pull request #747
Opened 2024-12-13 20:56 UTC by feg-adhoc

2025-01-09 12:05 UTC, rov-adhoc approved these changes

2025-01-15 21:18 UTC, tate11 commented
Thank you for your effort. Gives a date error
 time data '' does not match format '%d/%m/%Y'

<record id="garanti_statement_map" model="account.statement.import.sheet.mapping">
        <field name="name">Garanti Bankası</field>
        <field name="footer_lines_skip_count">0</field>
        <field name="header_lines_skip_count">1</field>
        <field name="float_thousands_sep">comma</field>
        <field name="float_decimal_sep">dot</field>
        <field name="delimiter">comma</field>
        <field name="quotechar">"</field>
        <field name="timestamp_format">%d/%m/%Y</field>
        <field name="timestamp_column">Date</field>
        <field name="amount_type">simple_value</field>
        <field name="amount_column">Amount</field>
<!--        <field name="original_currency_column">Currency</field>-->
<!--        <field name="original_amount_column">Amount Currency</field>-->
        <field name="description_column">Label</field>
<!--        <field name="partner_name_column">Partner Name</field>-->
<!--        <field name="bank_account_column">Bank Account</field>-->
    </record>

2025-02-04 14:44 UTC, feg-adhoc commented
Hello @tate11 ! Thank you for your feedback. Could you please specify how the file you used for testing is structured and how the mapping is configured? I am unable to reproduce the error.

2025-02-04 16:16 UTC, tate11 commented
> Hello @tate11 ! Thank you for your feedback. Could you please specify how the file you used for testing is structured and how the mapping is configured? I am unable to reproduce the error.

In Turkey, the date is used as day/month/year. It gives an error while importing like this.

2025-02-04 18:03 UTC, feg-adhoc commented
@tate11 You need to change the mapping configuration and set the timestamp format field to %d/%m/%Y, and it will work correctly.

2025-02-04 20:49 UTC, tate11 commented
> @tate11 You need to change the mapping configuration and set the timestamp format field to %d/%m/%Y, and it will work correctly.
https://github.com/OCA/bank-statement-import/pull/747#issuecomment-2593957450 
I tried this when we opened the issue .I opened this issue on top of that

2025-02-25 15:25 UTC, feg-adhoc commented
Hello @tate11 getting back to this… The tests you ran, were they done before the latest code changes? If so, it might be worth checking again with the updated version. Also, could you please share the sample bank CSV file? That would help me take a closer look.

2025-02-26 07:01 UTC, tate11 commented
> Hello @tate11 getting back to this… The tests you ran, were they done before the latest code changes? If so, it might be worth checking again with the updated version. Also, could you please share the sample bank CSV file? That would help me take a closer look.

Thank you very much I tested the latest status today and it works. 
[Screenshot 2025-02-26 at 09-58-11 BNK1 sample bank statement-01111.xls](https://github.com/user-attachments/files/18978845/Screenshot.2025-02-26.at.09-58-11.BNK1.sample.bank.statement-01111.xls)

2025-02-28 12:26 UTC, matteotrubini commented on account_statement_import_sheet_file/models/account_statement_import_sheet_parser.py
> +            if currency != currency_code:
```suggestion
            if currency.lower() != currency_code.lower():
```
Avoid skipping lines just because 'eur' != 'EUR'
Ref.: https://github.com/OCA/bank-statement-import/pull/764

2025-03-18 14:01 UTC, rov-adhoc approved these changes

2025-04-09 06:37 UTC, matteotrubini approved these changes

2025-04-09 06:46 UTC, pedrobaeza commented on account_statement_import_sheet_file/models/account_statement_import.py
> +                    return
Why this change?

2025-04-09 06:47 UTC, pedrobaeza commented
/ocabot migration account_statement_import_sheet_file

2025-04-10 22:46 UTC, feg-adhoc commented on account_statement_import_sheet_file/models/account_statement_import.py
> +                    return
Because when the 'raise' was triggered in v18, it would stop the test execution.

2025-04-25 21:11 UTC, rov-adhoc approved these changes

2025-05-08 11:33 UTC, AbhishekkumarReddy commented
Can someone merge this PR ??

2025-06-11 13:14 UTC, ByteMeAsap approved these changes
LGTM!! Can we have this merged?

2025-06-18 06:48 UTC, pedrobaeza commented
This PR contains a merge commit, which is not correct, and it also includes an extra commit for supporting XLS, which shouldn't be part of the migration. Can you please remove both and add #804 ?

2025-06-30 13:53 UTC, jbaudoux commented
I created this fix https://github.com/OCA/bank-statement-import/pull/805
that you can integrate here from https://github.com/jbaudoux/bank-statement-import/commit/197938159b0f60ded30d6188e06a1fa0b2f6b2af
as I cannot open a PR on your repo

2025-07-08 14:38 UTC, AquaMCU commented
Do we need to do something or will this pull request be merged automatically?

2025-07-14 09:04 UTC, BhaveshHeliconia commented
@feg-adhoc : I need to test some cases on runbot, so can you please enable runbot?
(Tried to import excel file with only 3 lines, but it's taking too much time right now(approximately 2-3 minutes), so need to verify this issue on runbot)

2025-07-16 21:37 UTC, AquaMCU commented
I just imported 2 years of bank statements in csv with this module in ODOO 18... Worked perfect

2025-07-27 17:17 UTC, Daemo00 requested changes
Thanks for this migration!
Please merge commits according to https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate, tirght now there are many bots' commits that shouldn't be there: 
<img width="1203" height="221" alt="image" src="https://github.com/user-attachments/assets/e7a5c3ba-1b4d-44ae-a347-b80325c3ffa4" />


I see that after the migration commit https://github.com/OCA/bank-statement-import/pull/747/commits/a186b28205ddfe6508b475029c07e7d19b968e33 there is another commit https://github.com/OCA/bank-statement-import/pull/747/commits/35b0cd316da34db08edc5029c8ff8830d226fcac:
<img width="1203" height="147" alt="image" src="https://github.com/user-attachments/assets/25f4b6d1-aea5-46e8-a5e3-1a7cdd58efff" />

could you please remove it?
In the migration PR there should only be what is needed for the migration, you'll be able to propose it again in anonther PR after the migrated module is merged.

Also note that https://github.com/OCA/bank-statement-import/commit/c4c48edbb6b9db069c841a2403e37c9ddad23822 is missing, please include it.

2025-07-27 17:17 UTC, Daemo00 commented on account_statement_import_sheet_file/tests/test_account_statement_import_sheet_file.py
> +                account_statement_import_sheet_file_test=True
As you noticed, the context was not matching anything and fixing it causes the tests to stop because an exception that is not a `UserError` is raised.

In my opinion you have a few different ways to resolve this situation:
- fix it: set the correct context as you have done, and catch the correct exception instead of `UserError`
- keep it: remove this change and the `return`/`raise` substitution, and let the tests behave as in `17.0`.
  The context `account_statement_import_txt_xlsx_test` is ignored, a `UserError` is raised.

In my opinion they are both acceptable, but using the correct context and just `return`ing instead of `raise`ing in the only place it is used (that what the current implementation does) does not seem very useful to me.

2025-07-27 17:17 UTC, Daemo00 commented on account_statement_import_sheet_file/tests/test_account_statement_import_sheet_file.py
> +                account_statement_import_sheet_file_test=True
Same as above

2025-07-27 17:28 UTC, Daemo00 commented
For some reason the maintainer of the module @alexey-pelykh hasn't been mentioned 🤷🏻

2025-08-03 20:08 UTC, tate11 commented
> For some reason the maintainer of the module @alexey-pelykh hasn't been mentioned 🤷🏻

Yes, it hasn't been mentioned since v16, and it wasn't there before that either. The Maintainers OCA, is interesting.

2025-08-12 11:14 UTC, carlos-lopez-tecnativa commented
Please include https://github.com/OCA/bank-statement-import/pull/821

2025-08-12 16:04 UTC, cvinh requested changes
I'm putting a preventive review because we have a use case that does not work here (csv file with header and footer lines to skip)
We're working on it here https://github.com/OCA/bank-statement-import/pull/819

2025-08-31 13:07 UTC, NICO-SOLUTIONS commented
Just checking in on this PR - any updates or feedback that still needs to be addressed?

2025-09-15 20:41 UTC, len-foss approved these changes
LGTM

2025-09-18 05:28 UTC, pedrobaeza commented
@cvinh @Daemo00 can you update your reviews?

2025-09-18 13:02 UTC, victoralmau requested changes
Please, cherry-pick https://github.com/OCA/bank-statement-import/pull/821 to commit history (before migration commit)

2025-09-18 13:02 UTC, victoralmau commented on account_statement_import_sheet_file/tests/test_account_statement_import_sheet_file.py
> +
```suggestion
from odoo.addons.base.tests.common import BaseCommon

class TestAccountStatementImportSheetFile(BaseCommon):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
```

2025-09-18 13:02 UTC, victoralmau commented on account_statement_import_sheet_file/tests/test_account_statement_import_sheet_file.py
> +        )
```suggestion
```
This shouldn't be necessary, right?

2025-09-18 13:13 UTC, cvinh commented
> @cvinh @Daemo00 can you update your reviews?

We have quite big fix here on v16 here https://github.com/OCA/bank-statement-import/pull/819 that will have to be forwarded I'm afraid.
I discussed yesterday with @mondot who will finish the review soon.
Maybe some of you can review as well

2025-09-18 14:00 UTC, Daemo00 commented
> @cvinh @Daemo00 can you update your reviews?

Sure, I'll be able to have a look at this this weekend or next week.
Please don't forget to re-request the review using the GitHub button (see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews#re-requesting-a-review)

2025-09-28 18:21 UTC, Daemo00 requested changes
Nothing from my last review https://github.com/OCA/bank-statement-import/pull/747#pullrequestreview-3059598192 has been addressed or replied to.

2025-10-13 15:04 UTC, anajuaristi approved these changes

2025-10-13 15:05 UTC, anajuaristi commented
Functional test V18 LGTM 👍

2025-10-13 16:34 UTC, cvinh commented
> Functional test V18 LGTM 👍

Thanks for testing @anajuaristi can you confirm you tested csv files with multiple header lines and footer lines ?
AFAIK it fails with that type of file
Please review https://github.com/OCA/bank-statement-import/pull/819

2025-10-28 20:07 UTC, carlos-lopez-tecnativa requested changes
I see some comments from my colleague @victoralmau that are still pending, please check them.
I understand that there are PRs for version 16 to handle files with headers, but can this be forward-ported after the migration, or is there something blocking it, @cvinh?

2025-10-28 20:07 UTC, carlos-lopez-tecnativa commented on account_statement_import_sheet_file/tests/test_account_statement_import_sheet_file.py
> +
@feg-adhoc this is still pending

2025-10-28 20:07 UTC, carlos-lopez-tecnativa commented on account_statement_import_sheet_file/tests/test_account_statement_import_sheet_file.py
> +        )
And this

2025-11-06 13:16 UTC, feg-adhoc commented
@carlos-lopez-tecnativa Hi Carlos! I've applied the requested cherry-picks. I also confirmed that the changes you pointed to were already present in the code (which is likely why one of the commits was empty during the cherry-pick).

@pedrobaeza I believe this is ready to merge now!
Thanks!

2025-11-20 17:49 UTC, rov-adhoc approved these changes

2025-11-21 20:46 UTC, feg-adhoc commented
@OCA/banking-maintainers Hi! Could you help me merge this module?

2025-11-22 08:41 UTC, pedrobaeza commented
@feg-adhoc there are up to 4 persons requesting changes to you. Please check their comments.

2025-12-01 17:15 UTC, feg-adhoc commented
@pedrobaeza I've already made the necessary changes!

2025-12-01 17:16 UTC, rov-adhoc approved these changes

2025-12-01 19:55 UTC, pedrobaeza commented
The other persons should now review. Please ping them.

2025-12-01 20:00 UTC, rov-adhoc commented
@Daemo00 @carlos-lopez-tecnativa @victoralmau @cvinh 
Could you please take a look at @feg-adhoc’s PR when you have a moment? Thanks in advance!

2025-12-02 09:22 UTC, jbaudoux approved these changes
Could you also include this fix ?
* https://github.com/OCA/bank-statement-import/pull/805

I made a PR on your branch:
* https://github.com/adhoc-dev/bank-statement-import/pull/3

2025-12-03 17:27 UTC, klosll approved these changes

2025-12-05 14:07 UTC, Daemo00 requested changes
Nothing from my first review (more than 4 months ago) https://github.com/OCA/bank-statement-import/pull/747#pullrequestreview-3059598192 has been addressed or replied to.

The same was true when you requested a review update the last time (more than 2 months ago), see https://github.com/OCA/bank-statement-import/pull/747#pullrequestreview-3277278627.

2025-12-16 15:42 UTC, closed without merging

2025-12-16 15:42 UTC, pedrobaeza commented
As this pull request doesn't progress with the requested changes for a long time, including undesired commits from non-merged PRs, and missing other already landed commits, I have opened a new PR with a simple bare migration done rescuing latest 17.0 state. I have also included a tests refactoring reducing the lines of code to the half, as most of them were copy/paste from an initial test case that includes all the code instead of being in the setup. Please check it and let's finally finish this migration: #868